using System;
using System.IO;
using AdeCartAPI.Model;
using System.Reflection;
using AdeCartAPI.Service;
using AdeCartAPI.UserService;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;



namespace AdeCartAPI
{
    public class Startup
    {
        private string paystack_Secret = null;
        private string paystack_Endpoint = null;
        private string connectionString = null;
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            paystack_Secret = Configuration["paystack_Secret"];
            paystack_Endpoint = Configuration["paystack_Endpoint"];
            connectionString = Configuration["ConnectionStrings:AdeCart"];

            services.AddControllers();

            services.AddAuthentication();

            services.AddScoped<IAddress, AddressRepository>();
            services.AddScoped<ITemInterface, ItemRepository>();
            services.AddScoped<IOrderCart, OrderCartRepository>();
            services.AddScoped<IOrder, OrderRepository>();
            services.AddSingleton<SqlService>();
            services.AddScoped<AdeCartService>();
            services.AddDbContext<IdentityDb>(opts =>
            {
                opts.UseSqlServer(Configuration["ConnectionStrings:AdeCart"]).EnableSensitiveDataLogging();
            });
            services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
            services.Configure<IdentityOptions>(options =>
            {
                // Default Password settings.
                options.Password.RequiredLength = 6;
                options.Lockout.MaxFailedAccessAttempts = 3;
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromSeconds(30);
                options.User.RequireUniqueEmail = true;
                options.SignIn.RequireConfirmedEmail = true;
                options.SignIn.RequireConfirmedAccount = true;
               

            });
            services.AddIdentity<User, IdentityRole>().AddEntityFrameworkStores<IdentityDb>().AddSignInManager().AddDefaultTokenProviders();

            services.AddSwaggerGen(setupAction =>
            {
                setupAction.SwaggerDoc("AdeCartAPISpecification", new Microsoft.OpenApi.Models.OpenApiInfo()
                {
                    Title = "AdeCart Api",
                    Version = "1.0",
                    Description = "An Ecommerce API",
                    Contact = new Microsoft.OpenApi.Models.OpenApiContact()
                    {
                        Email = "adeolaaderibigbe09@gmail.com",
                        Name = "Adeola Aderibigbe",
                        Url = new Uri("https://twitter.com/addiexandria")

                    }


                });
                //Locate the XML file being generated by ASP.NET...
                var xmlCommentFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlCommentFile);
                //... and tell Swagger to use those XML comments.
                setupAction.IncludeXmlComments(xmlPath);
            });

            
            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.HttpOnly = true;

                options.LoginPath = PathString.Empty;
                options.AccessDeniedPath = PathString.Empty;
                //options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
            app.UseSwagger();
            app.UseSwaggerUI(setupAction =>
            {
                setupAction.SwaggerEndpoint("/swagger/AdeCartAPISpecification/swagger.json", "AdeCart API");
                setupAction.RoutePrefix = string.Empty;
            });

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
